spring.datasource.url=jdbc:postgresql://ep-muddy-hill-al3ia10m.c-3.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_K5s4jgRQNhzx
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=fiftysel@gmail.com
spring.mail.password=bhne rkgd vusm yiuj

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=8443

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=toutou
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=ticket-app
