spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=fiftysel@gmail.com
spring.mail.password=bhne rkgd vusm yiuj

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8443

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=toutou
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=ticket-app
